apiVersion: apps/v1
kind: Deployment
metadata:
  name: destination-service
  namespace: ecovista
spec:
  replicas: 1
  selector:
    matchLabels:
      app: destination-service
  template:
    metadata:
      labels:
        app: destination-service
    spec:
      containers:
      - name: destination-service
        image: ecovista-destination-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
        env:
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: SECRET_KEY
        readinessProbe:
          httpGet:
            path: /destinations
            port: 5001
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /destinations
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: destination-service
  namespace: ecovista
spec:
  selector:
    app: destination-service
  ports:
  - port: 5003
    targetPort: 5001
