apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecovista-ingress
  namespace: ecovista
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ecovista.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 3000
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 5001
      - path: /activity
        pathType: Prefix
        backend:
          service:
            name: activity-service
            port:
              number: 5002
      - path: /destinations
        pathType: Prefix
        backend:
          service:
            name: destination-service
            port:
              number: 5003
      - path: /reviews
        pathType: Prefix
        backend:
          service:
            name: review-service
            port:
              number: 5004
      - path: /travel-groups
        pathType: Prefix
        backend:
          service:
            name: travelgroup-service
            port:
              number: 5005
      - path: /users
        pathType: Prefix
        backend:
          service:
            name: user-service
            port:
              number: 5006
